env:
  global:
  - secure: A+jQGTwvAM6jzula1ZNSr8lDcGm0GCBx1Xr3vanhV2a22UqdH6H3Ras7cU+Ii8UHhQEeNeQl53TgWgE/V75fqeVv5zN9sCru2L230MwFbWuOmZW7DnTu/dHItqjoGu+67n9KlfGKFVtwD9ENX+mgjLjebHoN1A44BS+KbP3M16w=
  - secure: blZZrKSStJHa0QPnI+DyEX+NCdQEqBD8BNKyPSPv8EyBblP7rHtK3D/9pFBjJX0pieDhSmI6vOspK9x3RVmfzrcQpJuNkbcDAGuGrT9XxZVU6NTtpbAZ5goniWRCUkOwpwuQD/glzKDfjk0A7GQY5cggHcw6GJQBkUvBNHmJdhU=

language: node_js
node_js:
- '0.11'
before_script:
- npm install -g gulp
script: gulp build
after_success:
  "cd dist && find . -type f -exec curl --user $FTP_USER:$FTP_PW --ftp-create-dirs -T {} ftp://www.lurinfacts.ch/{} \\; && echo $FTP_USER && echo $FTP_PW "
